import small0 from "./AllTrajectoryData/trajectoryData0.json";
// import small1 from "./AllTrajectoryData/trajectoryData1.json";
// import small2 from "./AllTrajectoryData/trajectoryData2.json";
// import small3 from "./AllTrajectoryData/trajectoryData3.json";
// import small4 from "./AllTrajectoryData/trajectoryData4.json";
// import small5 from "./AllTrajectoryData/trajectoryData5.json";
// import small6 from "./AllTrajectoryData/trajectoryData6.json";
// import small7 from "./AllTrajectoryData/trajectoryData7.json";
// import small8 from "./AllTrajectoryData/trajectoryData8.json";
// import small9 from "./AllTrajectoryData/trajectoryData9.json";
// import small10 from "./AllTrajectoryData/trajectoryData10.json";
// import small11 from "./AllTrajectoryData/trajectoryData11.json";
// import small12 from "./AllTrajectoryData/trajectoryData12.json";
// import small13 from "./AllTrajectoryData/trajectoryData13.json";
// import small14 from "./AllTrajectoryData/trajectoryData14.json";
// import small15 from "./AllTrajectoryData/trajectoryData15.json";
// import small16 from "./AllTrajectoryData/trajectoryData16.json";
// import small17 from "./AllTrajectoryData/trajectoryData17.json";
// import small18 from "./AllTrajectoryData/trajectoryData18.json";
// import small19 from "./AllTrajectoryData/trajectoryData19.json";
// import small20 from "./AllTrajectoryData/trajectoryData20.json";
// import small21 from "./AllTrajectoryData/trajectoryData21.json";
// import small22 from "./AllTrajectoryData/trajectoryData22.json";
// import small23 from "./AllTrajectoryData/trajectoryData23.json";
// import small24 from "./AllTrajectoryData/trajectoryData24.json";

export const dat0 = small0;
// export const dat1 = small1;
// export const dat2 = small2;
// export const dat3 = small3;
// export const dat4 = small4;
// export const dat5 = small5;
// export const dat6 = small6;
// export const dat7 = small7;
// export const dat8 = small8;
// export const dat9 = small9;
// export const dat10 = small10;
// export const dat11 = small11;
// export const dat12 = small12;
// export const dat13 = small13;
// export const dat14 = small14;
// export const dat15 = small15;
// export const dat16 = small16;
// export const dat17 = small17;
// export const dat18 = small18;
// export const dat19 = small19;
// export const dat20 = small20;
// export const dat21 = small21;
// export const dat22 = small22;
// export const dat23 = small23;
// export const dat24 = small24;
